const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec"]


// States
// NODE_DELETED
// NODE_CREATED
// NODE_NAME_CHANGE
// NODE_SAFE
// NODE_STUCK
// NODE_COMPROMISED
// NODE_STATE_CHANGE
// NODE_EXIT
// NODE_LOCATION_CHANGED
// FLOOR_CREATED
// FLOOR_DELETED
// FLOOR_NAME_CHANGE
// FLOOR_RELOCATED
// FLOOR_IMAGE_UPLOADED
// BUILDING_CREATED
// BUILDING_DELETED
// BUILDING_NAME_CHANGE